services:
  db:
    image: postgres:15
    container_name: snapcode-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - snapcode_db_postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  be:
    build:
      context: ./be
    container_name: snapcode-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - be/.env
    volumes:
      - ./be:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  snapcode_db_postgres:
